#!/usr/bin/env php
<?php

echo "Preparing Laravel organizer...." . PHP_EOL;

$basePath = __DIR__ . '/../../../';

$directories = ['Exceptions', 'Contracts', 'Services', 'EventsListeners', 'Managers', 'Models', 'Repositories', 'Traits', 'Macros', 'Helpers'];

foreach ($directories as $directory) {
    if (! is_dir($directoryPath = $basePath . 'app/' . $directory)) {
        mkdir($directoryPath);
    }
}

function recursive_copy($src,$dst) { 
    $dir = opendir($src); 
    @mkdir($dst); 
    while(false !== ( $file = readdir($dir)) ) { 
        if (( $file != '.' ) && ( $file != '..' )) { 
            if ( is_dir($src . '/' . $file) ) { 
                recursive_copy($src . '/' . $file,$dst . '/' . $file); 
            } 
            else { 
                copy($src . '/' . $file,$dst . '/' . $file); 
            } 
        } 
    } 
    closedir($dir); 
} 

// copy organizer files
recursive_copy(__DIR__ .'/files', $basePath);

echo 'Done!';